casbin/pycasbin

- casbin/config/config.py
- casbin/model/model.py
- casbin/model/policy.py
- casbin/util/expression.py
Fixed bug related to load config from text
> Fixed bugs to allow reinit model and enforcer in async mode

- tests/test_enforcer.py
> Add tests for rbac and empty policies

- casbin/model/assertion.py
Fix issue #23 
Test output:
```
2019-07-18 23:42:43,738 - INFO - Model:
2019-07-18 23:42:43,738 - INFO - r.r: sub, obj, act
2019-07-18 23:42:43,738 - INFO - p.p: sub, obj, act
2019-07-18 23:42:43,738 - INFO - e.e: some(where (p_eft == allow))
2019-07-18 23:42:43,738 - INFO - m.m: r_sub == r_obj.Owner
2019-07-18 23:42:43,739 - INFO - Request: alice, {'Owner': 'alice', 'id': 'data1'}, write ---> True
.....................
----------------------------------------------------------------------
Ran 21 tests in 0.030s
OK
```
> Change Assertion class attributes 

- casbin/persist/adapter.py
> Fix the add_policy method def in the Adapter intf

- casbin/core_enforcer.py
- casbin/rbac/default_role_manager/role_manager.py
Some errors/exceptions are being returned instead of `raise` being used.
> Fix: raise instead of returning exceptions.

- casbin/model/model.py
- examples/basic_model_without_spaces.conf
- tests/test_enforcer.py
Referring to the issue and PR, its time that we bring this support to pycasbin also.
https://github.com/casbin/casbin/pull/413
https://github.com/casbin/casbin/issues/412
> Added support for without space CONF model.

- casbin/internal_enforcer.py
- casbin/management_enforcer.py
- casbin/model/policy.py
- casbin/persist/batch_adapter.py
- tests/model/test_policy.py
- tests/test_management_api.py
Signed-off-by: Andy Xia <118010339@link.cuhk.edu.cn>
> Add batch function

- casbin/core_enforcer.py
- casbin/util/util.py
- tests/util/test_util.py
Signed-off-by: Andy Xia <118010339@link.cuhk.edu.cn>
> Add eval function

- casbin/core_enforcer.py
> Added support for filtered policies

- casbin/persist/adapter.py
- casbin/persist/adapters/file_adapter.py
> fix: added filtered policy functions to defaults

- casbin/core_enforcer.py
Fix: https://github.com/casbin/pycasbin/issues/77
> add "!" operator

- casbin/rbac/default_role_manager/role_manager.py
- examples/rbac_with_pattern_model.conf
- examples/rbac_with_pattern_policy.csv
- tests/test_enforcer.py
Fix: https://github.com/casbin/pycasbin/issues/74
> support matching function in default role manager

- casbin/core_enforcer.py
- casbin/util/util.py
- examples/abac_multiple_rules_model.conf
- examples/abac_multiple_rules_policy.csv
- examples/abac_rule_model.conf
- examples/abac_rule_policy.csv
- tests/test_enforcer.py
- tests/util/test_util.py
Fix: #57
Replaces: #93, #68
Signed-off-by: Andreas Bichinger <andreas.bichinger@gmail.com>
> feat: add eval function

- casbin/__init__.py
- casbin/core_enforcer.py
- casbin/synced_enforcer.py
- casbin/util/rwlock.py
- tests/test_enforcer.py
- tests/test_management_api.py
- tests/test_model_benchmark.py
- tests/test_rbac_api.py
- tests/util/test_rwlock.py
Fix: https://github.com/casbin/pycasbin/issues/98
> feat: add synced enforcer

- casbin/core_enforcer.py
- casbin/persist/__init__.py
- casbin/persist/adapter.py
- casbin/persist/adapter_filtered.py
- casbin/persist/adapters/__init__.py
- casbin/persist/adapters/adapter_filtered.py
- casbin/persist/adapters/file_adapter.py
- casbin/util/builtin_operators.py
- test_filter.py
load_filtered_policy need to modify
> feat: add filter_adapter

- .github/semantic.yml
Fix: https://github.com/casbin/pycasbin/issues/106
> chore: add senmantic.yml

- casbin/rbac/default_role_manager/role_manager.py
- tests/rbac/test_role_manager.py
> fix: role manager with matching_func

- casbin/internal_enforcer.py
- casbin/management_enforcer.py
- casbin/model/policy.py
- tests/model/test_policy.py
Fix: https://github.com/casbin/pycasbin/issues/105
> feat: add update_policy()

- casbin/__init__.py
- casbin/core_enforcer.py
- casbin/enforcer.py
- casbin/model/policy.py
- casbin/rbac/default_role_manager/role_manager.py
- casbin/synced_enforcer.py
- casbin/util/__init__.py
- tests/test_enforcer.py
Fix: https://github.com/casbin/pycasbin/issues/121
Fix: https://github.com/casbin/pycasbin/issues/103
> feat: add AddNamedDomainMatchingFunc and AddNamedMatchingFunc to enforcer

- casbin/core_enforcer.py
ref to: 
> This line should be outside the `for` loop.
> _Originally posted by @techoner in https://github.com/casbin/pycasbin/pull/122#discussion_r580756955_
> perf: reposition build_role_links()

- casbin/config/config.py
- tests/config/test_config.py
I have added code to lookup the value of provided key in config and to convert this value to respective types.
> perf: Added code to convert config value to different types

- casbin/persist/dispatcher.py
Added code for dispatcher class.
> feat: Added dispatcher class

- casbin/__init__.py
- casbin/distributed_enforcer.py
- casbin/internal_enforcer.py
- casbin/model/assertion.py
- casbin/model/model.py
- casbin/model/policy.py
- casbin/model/policy_op.py
- casbin/persist/adapters/update_adapter.py
- casbin/rbac/default_role_manager/role_manager.py
- casbin/synced_enforcer.py
- tests/test_distributed_api.py
I have added distributed enforcer along with unit tests for distributed enforcer. I have also added some functions that were absent in other enforcer files but were needed directly or indirectly by distributed enforcer. 
I have checked it completely but if there is any error please tell me, I'll fix it.
> feat: added distributed enforcer file along with respective unit tests

- casbin/core_enforcer.py
- casbin/synced_enforcer.py
- tests/test_enforcer.py
> refactor: rename enforceEx() to enforce_ex()

- casbin/core_enforcer.py
- casbin/synced_enforcer.py
- tests/test_enforcer.py
> Revert "refactor: rename enforceEx() to enforce_ex()"

- casbin/core_enforcer.py
> perf: remove unused variable

- setup.py
Fix: https://github.com/casbin/pycasbin/issues/151
automated the install_requires parsing process
> fix: optimized install_requires parsing process

- casbin/core_enforcer.py
> fix: enforce_ex now works fine when it was disabled

- casbin/model/function.py
> fix: function 'keyMatch3' not defined

- casbin/model/policy.py
- examples/priority_model_explicit.conf
- examples/priority_policy_explicit.csv
- tests/model/test_policy.py
Signed-off-by: Shen Yixuan <1479765922@qq.com>
Pass the tests in my workflow with the `build.yml`.
> refactor: refactor ManagementEnforcer.update_policy and update_policies

- .github/workflows/build.yml
- casbin/enforcer.py
- tests/test_rbac_api.py
> fix: get_implicit_users_for_permission()

- .github/workflows/build.yml
> ci: use "github-actions" to send release notice

- casbin/core_enforcer.py
> feat: add API for role manager besides "g"

- casbin/core_enforcer.py
- casbin/model/model.py
- casbin/model/policy.py
- tests/test_enforcer.py
I think the model/policy structure will look simpler if this change is made.
> refactor: modify model/policy structure

- casbin/persist/adapters/__init__.py
- casbin/persist/adapters/update_adapter.py
Need to finish this interface to address: [#41](https://github.com/pycasbin/sqlalchemy-adapter/issues/41)
> feat: finish up UpdateAdapter

- casbin/persist/watcher.py
- casbin/persist/watcher_ex.py
- casbin/persist/watcher_update.py
Add Watcher interfaces to match Casbin's implementation.
> feat: PyCasbin Watcher interfaces added

- casbin/model/function.py
> fix: fm instance property

- casbin/internal_enforcer.py
- casbin/management_enforcer.py
Signed-off-by: abingcbc <abingcbc626@gmail.com>
fix: https://github.com/casbin/pycasbin/issues/208
> fix: replace build_role_links with build_incremental_role_links

- tests/test_enforcer.py
Signed-off-by: sallycaoyu <sallycaoyu@gmail.com>
Fixed GitHub Actions Super Linter Error in Issue #218.
Fix: https://github.com/casbin/pycasbin/issues/218
> fix: linter bug in test_enforcer.py

- casbin/__init__.py
- casbin/frontend.py
- casbin/model/model.py
- tests/test_frontend.py
Signed-off-by: abingcbc <abingcbc626@gmail.com>
Fix: https://github.com/casbin/pycasbin/issues/224
Refer to: 
1. https://github.com/casbin/casbin.core.js/blob/4d7b0b808517df2ece2aefa3db42658522107437/src/frontend.ts
2. https://github.com/casbin/casbin.core.js/blob/4d7b0b808517df2ece2aefa3db42658522107437/test/frontend.test.ts
3. https://github.com/casbin/casbin/blob/master/frontend.go
> feat: casbin_js_get_permission_for_user

- casbin/enforcer.py
- casbin/rbac/default_role_manager/role_manager.py
Fix: https://github.com/sheny1xuan/pycasbin/pull/1#issuecomment-992048061
https://github.com/casbin/pycasbin/pull/228#issuecomment-992071103
Signed-off-by: Andreas Bichinger <andreas.bichinger@gmail.com>
> perf: judge whether use domain_matching_func

- casbin/core_enforcer.py
Fix: https://github.com/casbin/pycasbin/issues/251
> fix: load policy override role manager

- casbin/internal_enforcer.py
- casbin/management_enforcer.py
- casbin/persist/adapters/update_adapter.py
- tests/test_management_api.py
Fix: https://github.com/pycasbin/sqlalchemy-adapter/issues/53
> feat: update_filtered_policies

- .github/workflows/build.yml
- casbin/config/config.py
- casbin/core_enforcer.py
- casbin/distributed_enforcer.py
- casbin/enforcer.py
- casbin/internal_enforcer.py
- casbin/management_enforcer.py
- casbin/model/assertion.py
- casbin/model/model.py
- casbin/model/policy.py
- casbin/persist/adapters/update_adapter.py
- casbin/persist/watcher_ex.py
- casbin/rbac/default_role_manager/role_manager.py
- casbin/synced_enforcer.py
- pyproject.toml
- tests/benchmarks/benchmark_model.py
- tests/config/test_config.py
- tests/rbac/test_role_manager.py
- tests/test_distributed_api.py
- tests/test_enforcer.py
- tests/test_filter.py
- tests/test_management_api.py
- tests/test_rbac_api.py
- tests/util/test_builtin_operators.py
- tests/util/test_util.py
- Added lint config file and configured workflow for linting
- Lint files with the latest lint config
- ref: #249
> fix: Configure Linting

- casbin/core_enforcer.py
> fix: update core_enforcer.py

- examples/globmatch_model.conf
- examples/globmatch_policy.csv
- tests/test_enforcer.py
no clear example of glob match
> fix: add more example and unit test for glob_match()

- .github/workflows/build.yml
- examples/performance/rbac_with_pattern_large_scale_model.conf
- examples/performance/rbac_with_pattern_large_scale_policy.csv
- tests/benchmarks/benchmark_management_api.py
- tests/benchmarks/benchmark_model.py
- tests/benchmarks/benchmark_role_manager.py
fix https://github.com/casbin/casbin/issues/1049
The names of the benchmark cases are the snake case of corresponding ones in Casbin-core.
> test: update the benchmark test cases

- casbin/util/builtin_operators.py
- tests/util/test_builtin_operators.py
Add key_get(), key_get2() and key_get3() for builtin_operators.py
> fix: add key_get() for builtin_operators

- casbin/core_enforcer.py
- casbin/internal_enforcer.py
> feat: add watcher-ex call

- casbin/core_enforcer.py
- casbin/internal_enforcer.py
- casbin/persist/adapters/adapter_filtered.py
- tests/benchmarks/benchmark_management_api.py
reference: [https://google.github.io/styleguide/pyguide.html](https://google.github.io/styleguide/pyguide.html)
> fix: polish import grammar and remove some useless package

- casbin/synced_enforcer.py
> fix: fix typo in remove_grouping_policies() API

- casbin/persist/adapter.py
Reverts casbin/pycasbin#259
Fix: https://github.com/casbin/pycasbin/issues/289
> feat: revert "fix: avoid duplicate adapter entries"

- casbin/core_enforcer.py
- casbin/synced_enforcer.py
- tests/test_enforcer.py
> feat: Add batch_enforce() API

- casbin/persist/adapters/string_adapter.py
- tests/persist/test_string_adapter.py
refer to: https://github.com/casbin/casbin/pull/1201
> feat: add string adapter

- casbin/__init__.py
- casbin/core_enforcer.py
- casbin/distributed_enforcer.py
- casbin/model/assertion.py
- casbin/model/policy.py
- casbin/rbac/default_role_manager/role_manager.py
- casbin/util/log.py
Use python logging dict_config to achieve more precise log level and format control
> feat: update logger for more precise log level and format control

- casbin/async_internal_enforcer.py
- casbin/constant/constants.py
- casbin/effect/__init__.py
- casbin/internal_enforcer.py
- casbin/model/assertion.py
- casbin/model/model.py
- casbin/synced_enforcer.py
- tests/test_rbac_api.py
refer to: https://github.com/casbin/casbin/pull/1041
> feat: add field_index_map and constant

- casbin/async_enforcer.py
- casbin/enforcer.py
- casbin/synced_enforcer.py
- examples/rbac_with_domains_policy2.csv
- tests/test_rbac_api.py
refer to: https://github.com/casbin/casbin/pull/1190
> feat: add get_all_roles_by_domain api

- casbin/async_enforcer.py
- casbin/enforcer.py
- casbin/model/policy.py
- casbin/synced_enforcer.py
- tests/test_rbac_api.py
refer to: https://github.com/casbin/casbin/pull/1245
> feat: add get_implicit_users_for_resource api

- casbin/model/model.py
- tests/model/test_model.py
Fixed the `subjectPriority` sorting algorithm and support for checking the subject role link loop.
> feat: Fixed the `subjectPriority` sorting algorithm and support for checking the subject role link loop

- casbin/core_enforcer.py
fix: https://github.com/casbin/pycasbin/issues/319
> feat: disable logger when log is not enabled

- casbin/core_enforcer.py
- casbin/management_enforcer.py
- casbin/model/assertion.py
- casbin/model/function.py
- casbin/model/model.py
- casbin/model/policy.py
- casbin/rbac/__init__.py
- casbin/rbac/default_role_manager/__init__.py
- casbin/rbac/default_role_manager/role_manager.py
- casbin/rbac/role_manager.py
- casbin/synced_enforcer.py
- casbin/util/builtin_operators.py
- examples/rbac_with_domain_temporal_roles_condition_policy.csv
- examples/rbac_with_domain_temporal_roles_model.conf
- examples/rbac_with_domain_temporal_roles_policy.csv
- examples/rbac_with_temporal_roles_condition_policy.csv
- examples/rbac_with_temporal_roles_model.conf
- examples/rbac_with_temporal_roles_policy.csv
- tests/test_enforcer.py
- tests/util/test_builtin_operators.py
refer to:https://github.com/casbin/casbin/pull/1294
> feat: add temporal role model

- casbin/model/policy.py
> fix: KeyError: 'g' when build_role_links

- casbin/core_enforcer.py
fix: https://github.com/casbin/pycasbin/issues/368
> feat: fix bug that "!=" in policies is replaced with "not="

- casbin/model/policy.py
add_policies can update policy_map
Fix: https://github.com/casbin/pycasbin/issues/356
> feat: fix the bug that add_policies does not update policy_map

- casbin/management_enforcer.py
- casbin/persist/adapters/file_adapter.py
- casbin/synced_enforcer.py
- tests/test_management_api.py
Fix: https://github.com/casbin/pycasbin/issues/388
feat: add add_grouping_policies_ex and add_named_grouping_policies_ex API
> feat: add add_grouping_policies_ex and add_named_grouping_policies_ex APIs
