casbin/enforcer.py
tests/test_enforcer.py

Fixed bug when logging was enabled and passing in objects as parameters into enforce

Fix logging problem when passing objects as parameters into enforce()

---

casbin/enforcer.py

Empty policy list causes error
NameNotDefined 'p_sub' is not defined for expression ...
because the token is represented by tuple in this string

fix for empty policy list

---

casbin/log/default_logger.py
casbin/log/log.py

import casbin changed logging basic config, which is not excepted.
Fix: https://github.com/casbin/pycasbin/issues/17

Fix global logging settings.

---

casbin/util/builtin_operators.py
casbin/util/util.py

Rewrote `casbin.util.util.array_remove_duplicates` function to be more faster and pythonic.
Benchmarks:
```
python -m timeit -n 100000 -r 10 'from casbin.util.util import array_remove_duplicates; array_remove_duplicates(["one", "one", "two", "two", "three"])'
100000 loops, best of 10: 2.49 usec per loop
python -m timeit -n 100000 -r 10 'from casbin.util.util import array_remove_duplicates; array_remove_duplicates(["one", "one", "two", "two", "three"])'
100000 loops, best of 10: 2.19 usec per loop
```
There are even more efficient implementation possible if order may not be preserved. Current implementation follows original implementation and preserves order.
Also i moved regular expressions to module level because regexp compilation is an extensive operation and it is recommended to do …

Code optimisation.

---

tests/model/test_policy.py

Fix issue #26 
Output
```
.2019-07-19 10:54:50,904 - INFO - test logprint
2019-07-19 10:54:50,904 - INFO - test log print
.....2019-07-19 10:54:50,906 - INFO - Model:
2019-07-19 10:54:50,906 - INFO - r.r: sub, obj, act
2019-07-19 10:54:50,906 - INFO - p.p: sub, obj, act
2019-07-19 10:54:50,906 - INFO - e.e: some(where (p_eft == allow))
2019-07-19 10:54:50,906 - INFO - m.m: r_sub == r_obj.Owner
2019-07-19 10:54:50,906 - INFO - Request: alice, {'Owner': 'alice', 'id': 'data1'}, write ---> True
............................
----------------------------------------------------------------------
Ran 34 tests in 0.022s
OK
```

Modularize tests code

---

casbin/config/config.py
tests/config/test.ini
tests/config/test_config.py

- The actual code strips the multiline char but sometimes
it leads to syntax errors because not compatible chars may
result appended.

Fix syntax errors on multiline config sentences

---

casbin/model/assertion.py

We currently have a need for a `count == 5` but I see no reason where there can't be an arbitrary number of arguments here.

Add support for N role link values

---

casbin/util/builtin_operators.py
tests/util/test_builtin_operators.py

Signed-off-by: Zixuan Liu <nodeces@gmail.com>
- fix `keyMatch2` doesn't work - `keyMatch2("/foo", "/")` returns `True`
- fix `ipMatch`, It doesn't support CIDR model - `ipMatch("192.168.2.123", "192.168.2.0/16")` 
- improve KeyMatch to avoid endless loop - `keyMatch2("/:/all", "/:/all")`, `keyMatch2("/{/all", "/{/all")`
- add more tests
fixes: #84, #87

fix: improve KeyMatch and add tests

---

casbin/model/function.py
casbin/util/builtin_operators.py
tests/util/test_builtin_operators.py

Hi !
This PR will add the function globMatch in the models.
It's based on the fnmatch module and the behavior will differ a bit from the globMatch function available in https://github.com/casbin/casbin. For example `globMatch("/foo/bar/123", "/foo*")` returns True in pycasbin but False in casbin
Don't hesitate to let me know if you have any question.
Thanks !

feat: add glob pattern matching using fnmatch module

---

casbin/model/policy.py

perf: remove duplicated check

---

.gitignore
casbin/enforcer.py
casbin/management_enforcer.py
casbin/model/assertion.py
casbin/model/policy.py
casbin/rbac/default_role_manager/role_manager.py
casbin/util/util.py
test_filter.py

Hi !
I closed my previous pull request for this (https://github.com/casbin/pycasbin/pull/125) because I messed up my files and I redid everything from scratch (my apologies for this)....
This PR is about a bunch of small modifications that takes advantages of some python idioms and should slightly improve performances.
I tried not to break any logic, and all tests are working, but I might have missed a few things here or there.
Many thanks !

perf: refacto & slight performance improvements

---

casbin/core_enforcer.py

While creating a new Enforcer, instead of providing string or Model object in place of model, if user provides something else, let's say an integer:
```
a = casbin.persist.adapters.FileAdapter("basic_policy.csv")
e = casbin.Enforcer(2, a)
```
then following exception is being thrown
`AttributeError: 'int' object has no attribute 'print_model'`
To avoid this condition I have added checks in `init_with_model_and_adapter`.

fix: Added checks in init_with_model_and_adapter in CoreEnforcer

---

casbin/util/util.py

The use of `\.` is to prevent `p.rule` from being converted to `p_r_le`
Signed-off-by: lzxin <cnlzxin@gmail.com>

fix: r.user.name -> r_user_name instead of r_user.name in ABAC model

---

casbin/util/builtin_operators.py
requirements.txt
tests/util/test_builtin_operators.py

fix: #148 
ref to discussion at https://bugs.python.org/issue28718, it'll be complicated to implement it. 
So I have to introduce a new dependency `wcmatch`.

fix: replace fnmatch with wcmatch for glob match, keep same behavior with Go Casbin

---

casbin/core_enforcer.py
casbin/distributed_enforcer.py
casbin/model/assertion.py
casbin/model/policy.py
casbin/rbac/default_role_manager/role_manager.py

Fix: https://github.com/casbin/pycasbin/issues/119

feat: Use named loggers

---

casbin/synced_enforcer.py

SyncedEnforcer's `start_auto_load_policy()` only create a daemon thread, but not start it, so it's not working.

fix: start auto loading policy for SyncedEnforcer

---

casbin/core_enforcer.py
casbin/enforcer.py
casbin/rbac/default_role_manager/role_manager.py
casbin/util/builtin_operators.py
examples/rbac_with_all_pattern_model.conf
examples/rbac_with_all_pattern_policy.csv
examples/rbac_with_domain_pattern_model.conf
examples/rbac_with_domain_pattern_policy.csv
requirements.txt
tests/test_rbac_api.py
tests/util/test_rwlock.py

feat: add support for add_domain_matching_function

---

casbin/core_enforcer.py
casbin/synced_enforcer.py
casbin/util/util.py
examples/multiple_policy_definitions_model.conf
examples/multiple_policy_definitions_policy.csv
tests/test_enforcer.py

Fix: #180 
updated to match Casbin version [v2.35.0](https://github.com/casbin/casbin/releases/tag/v2.35.0)

feat: multiple request, policy, effect, matcher type support

---

setup.py

Added an encoding of "utf-8" to the read function for bypasing "charmap" error and achieving a smooth installation in a windows local system.

fix: added utf8 encoding

---

casbin/distributed_enforcer.py
casbin/model/policy.py

Signed-off-by: abingcbc <abingcbc626@gmail.com>
The input `field_values` of `remove_filtered_policy_returns` is like `("alice", "tom")`, but the one of `remove_filtered_policy_returns_effects` is like `(("alice", "tom"),)`.
Just use `field_values` but not `field_values[0]`. But it cannot pass the unit test, so we have to modify where it is used.
The only usage of `remove_filtered_policy_returns_effects` is `remove_filtered_policy_self`. In this function, the original codes didn't unwrap the `field_values` and directly pass it to `remove_filtered_policy_returns_effects`. So we can unwrap `field_values` here and keep the input consistent with `remove_filtered_policy`.

fix: remove_filtered_policy_returns_effects inconsistent input

---

casbin/core_enforcer.py
casbin/enforcer.py
casbin/rbac/default_role_manager/__init__.py
casbin/rbac/default_role_manager/role_manager.py
tests/rbac/test_role_manager.py
tests/test_distributed_api.py
tests/test_rbac_api.py

fix: reimplement default role manager

---

tests/test_enforcer.py

Fix: https://github.com/casbin/pycasbin/issues/215
Signed-off-by: sallycaoyu <sallycaoyu@gmail.com>

feat: port the test case of add_function() example to pycasbin

---

casbin/enforcer.py
casbin/synced_enforcer.py
examples/rbac_with_domains_without_policy_matcher.conf
examples/rbac_with_hierarchy_without_policy_domains.csv
tests/test_rbac_api.py

Fix: https://github.com/casbin/pycasbin/issues/214
Because of domain patterns in p records, we cannot filter policies by this kind of dynamic domains. 
`self.get_filtered_policy(0, user, domain)` .  
Thus we get empty permissions in this case.
Same goes policy records without domains

feat: ignore policies with domain when get_implicit_permissions_for_user

---

tests/util/test_builtin_operators.py

Signed-off-by: sallycaoyu <sallycaoyu@gmail.com>
Added test cases from Go to Python as suggested in Issue #148.
Fix: https://github.com/casbin/pycasbin/issues/148

fix: add glob_match() test cases from Go to Python

---

casbin/enforcer.py
examples/rbac_with_domain_and_policy_pattern_policy.csv
tests/test_management_api.py
tests/test_rbac_api.py

Fix: https://github.com/casbin/pycasbin/issues/227
Signed-off-by: timabilov <timabilov33@gmail.com>

feat: get implicit permissions filter policies domain by matching function

---

casbin/core_enforcer.py
casbin/model/model.py
examples/subject_priority_model.conf
examples/subject_priority_model_with_domain.conf
examples/subject_priority_policy.csv
examples/subject_priority_policy_with_domain.csv
tests/test_enforcer.py

Fix: https://github.com/casbin/pycasbin/issues/187

feat: subject priority

---

casbin/enforcer.py
casbin/synced_enforcer.py
examples/rbac_with_multiple_policy_model.conf
examples/rbac_with_multiple_policy_policy.csv
tests/test_rbac_api.py

Fix: #253 
fix the issue by add get_implicit_permissions_for_user_by_named_policy(), 
so user can get permissions with named ptypes.

fix: allow permissions management to use additional p-types

---

casbin/util/builtin_operators.py
requirements.txt
tests/util/test_builtin_operators.py

Fix: #148 
Reimplement the glob_match

fix: different behavior of glob_match from other casbin

---

casbin/management_enforcer.py
casbin/rbac/default_role_manager/role_manager.py

Fix: https://github.com/casbin/pycasbin/issues/250

fix: avoid raising exception in remove_grouping_policy

---

casbin/persist/adapter.py

fix: avoid duplicate adapter entries

---

tests/__init__.py
tests/benchmarks/__init__.py
tests/config/__init__.py
tests/model/__init__.py
tests/rbac/__init__.py
tests/util/__init__.py

When I tried to call the api in the tests module, I found it inconvenient to import test classes in the tests module. So I added import statements to the tests module so that all test classes can be imported at once.

fix: add import statement in tests module

---

requirements_dev.txt

Without pytest and pytest-benchmark, can't run benchmark locally

fix: add dependency for benchmark

---

casbin/synced_enforcer.py

At present if an exception occurs in the auto loader thread it kills the thread with no way of restarting it.  This means that even a recoverable error will kill the thread permanently - we've seen this on our own app were we temporarily lose connectivity with the DB.  Once connectivity is restored the auto loader is broken because the thread has died, forcing us to restart our app.

fix: catch exceptions in synced enforcer thread

---

casbin/core_enforcer.py

fix: https://github.com/casbin/pycasbin/issues/273

fix: load_policy changed the old model

---

casbin/synced_enforcer.py

Fixes a bug in (my own) https://github.com/casbin/pycasbin/pull/272 - syncedEnforcer doesn't have its own logger, it needs to use the Enforcer's logger.

fix: fix bug in autoloader error handling

---

README.md

You cannot jump to the corresponding chapter by clicking Persistence before because the chapter name has changed. Now it's ok.

docs: click Persistence jump to related catalogue

---

casbin/persist/adapter.py

Fix: https://github.com/casbin/pycasbin/issues/291

fix: support escaping comma inside quote in load_policy_line()'s CSV parsing

---

.github/workflows/build.yml
casbin/persist/adapter.py

This PR expands https://github.com/casbin/pycasbin/pull/292 to support parentheses, used in custom functions (https://casbin.org/docs/function#how-to-add-a-customized-function)

fix: load policy rule without splitting custom functions

---

setup.py

The wheels include the tests, due to the `find_packages` exclusion being subtle: it is a full package path glob, not just a prefix/parent package exclusion. This makes the appropriate adjustment to the `find_packages(exclude=...)` call to ensure they're not included.
See the "Important" note in https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#finding-simple-packages
```
curl -O https://files.pythonhosted.org/packages/a8/02/b6c6de2524add783af7be9b057baf8dc1cda62b4aa5cd8b7ea2ede500658/casbin-1.18.2-py3-none-any.whl
unzip -l casbin-1.18.2-py3-none-any.whl
#> ...
#>       637  04-06-2023 17:12   tests/benchmarks/__init__.py
#>      2882  04-06-2023 17:12   tests/benchmarks/benchmark_management_api.py
#> ...
#> ---------                     -------
#>    270392 …
```

fix: Exclude tests from package

---

setup.py

Fix: https://github.com/casbin/pycasbin/issues/295
Including the `README.md` as a top-level data file is unconventional and can interfere with other packages if they also accidentally include their `README.md`: installing both packages leads to the second one overwriting the `README.md` of the first one. (A lot of the casbin python packages interfere with each other like this.)
The contents of the README is available as the package's long description, which is included in its `METADATA` file.
In addition to that problem, running `python setup.py bdist_wheel` results in a warning, tangentially referencing this problem:
```
warning: install_data: setup script did not provide a directory for 'README.md' -- installing right in 'build/bdist.macosx-11.4-arm64/wheel/casbin-1.18.2.data/data'
``` …

fix: Stop including README as top-level data file in package

---

casbin/core_enforcer.py
casbin/internal_enforcer.py
tests/test_watcher_ex.py

Add auto_notify_watcher to control whether to save a policy rule automatically notify the watcher when it is added or removed.
refer to: https://github.com/casbin/casbin/pull/366

feat: add auto_notify_watcher to core enforcer

---

casbin/model/model.py

Fixed using the rbac model subjectPriority policy, loading the policy failed when the role was not associated with the user

fix: Fixed using the rbac model subjectPriority policy, loading the policy failed when the role was not associated with the user

---

casbin/model/policy.py

Fix: https://github.com/casbin/pycasbin/issues/310
**Description**:
Fixes a bug in assigning an index to a new policy was added when using the priority effector. 
The bug is that when we loop from range(i, 0, -1), i stops at 1 ( since range is exclusive for the end parameter ), and hence we cant assign a policy to index 0 in this logic ( in case the newly added policy indeed has the lowest priority )
I swapped it for a simpler logic that bubbles up the inserted policy to the correct index. 
**Related Issue:**
https://github.com/casbin/pycasbin/issues/310
**Tests:**
Ran - python3 -m unittest discover
```
..['alice']
..............Request: bob, data1, read ---> False
Request: bob, data1, write ---> False
Request: bob, data2, read ---> False
............................................. …
```

fix: fix bug in add policy for priority effectors

---

casbin/__init__.py
casbin/core_enforcer.py
casbin/distributed_enforcer.py
casbin/fast_enforcer.py
casbin/model/__init__.py
casbin/model/model_fast.py
casbin/model/policy_fast.py
tests/__init__.py
tests/model/__init__.py
tests/model/test_policy_fast.py
tests/test_enforcer_fast.py
tests/test_fast_enforcer.py

Replace: https://github.com/casbin/pycasbin/pull/285

feat: port fastbin to casbin

---

casbin/core_enforcer.py
casbin/util/log.py

Fix: https://github.com/casbin/pycasbin/issues/323

fix: disabled all logger

---

casbin/util/expression.py

SimpleEval class declares a class variable `ast_parsed_value` mean to store the parsed value. However, it is not used and instead, another variable is created in the constructor.

fix: use the predefined member

---

casbin/core_enforcer.py

Changed log level from "error" to "warning", to avoid triggering alerts in Sentry.

feat: change log level to warning

---

.releaserc.json
pyproject.toml

@leeqvip 
Ups! I forgot to add `pyproject.toml` to the assets of `@semantic-release/git`

chore: semantic-release commits pyproject.toml

---

casbin/async_internal_enforcer.py
tests/test_watcher_ex.py

AsyncEnforcer can now also await Watcher callbacks if they are Coroutines. Related to #340.
Fix: https://github.com/casbin/pycasbin/issues/340

feat: Added support for async watcher callbacks #340

---

casbin/fast_enforcer.py
tests/test_fast_enforcer.py

The FastEnforcer class has a check to see if `FastEnforcer._cache_key_order` is None. If None, the enforcer does not use the `fast_policy_filter` which provides significant performance enhancements. This is likely a bug, as `FastEnforcer._cache_key_order` refers to the class variable, and not the current instance's value. `self._cache_key_order` should be checked instead.
https://github.com/casbin/pycasbin/issues/336
https://github.com/casbin/pycasbin/issues/71

fix: FastEnforcer not fast

---

casbin/constant/constants.py
casbin/management_enforcer.py
tests/test_management_api.py

`get_all_named_{things}` functions (things can be `actions`, `subjects`, `roles`) uses hard-coded index for getting "things" from policies, which causes wrong result when using RBAC with domains mode (which a new field `domain` is inserted to the index 1).
The PR does:
- use `Model.get_field_index` for getting correct field index when getting the actions, subjects
- a new testcase is added
`get_all_named_{things}` functions (things can be `actions`, `subjects`, `roles`) use fixed field index while fetching the corresponding resources, which causes incorrect behavior when the field indexes change.
According to [the documentation](https://casbin.org/docs/rbac-with-domains), the RBAC mode with domains have the convenient putting `domain` as the second param of a policy, while the `subject` …

fix: field_index is incorrect in RBAC with domains mode (#345)

---

casbin/persist/adapters/filtered_file_adapter.py
tests/test_filter.py

Fix: https://github.com/casbin/pycasbin/issues/361
- The old logic's handling of the g rules is too simplistic. If filter[1] is a null value (indicating there are no g rules to filter), the old logic will still continue to call filter_words for filtering, which may lead to unnecessary misfiltering.
- When filtering g rules, the filter may be a null value. The old logic did not explicitly handle this situation, which could lead to all g rules being skipped (misfiltered).
1. Improved Filtering Logic:
- Refactored filter_line and filter_words to distinguish between p and g rules.
- Added explicit handling for empty filters, ensuring that g rules can still be loaded when adapter.filter.G is empty.
2. Optimized Role Rule Handling:
- Ensured that g rules are only filtered when adapter.filter.G …

feat: enhance FilteredFileAdapter to handle flexible filtering for policies and roles

---

casbin/persist/adapters/__init__.py

Fix: https://github.com/casbin/pycasbin/issues/358

feat: add StringAdapter's statement in init.py

---

README.md
casbin/core_enforcer.py
casbin/fast_enforcer.py

fix: https://github.com/casbin/pycasbin/issues/362

feat: add "logging_config" for PyCasbin logging

---

casbin/internal_enforcer.py
casbin/management_enforcer.py
casbin/model/policy.py
casbin/synced_enforcer.py
tests/test_management_api.py

Part of: https://github.com/casbin/pycasbin/issues/388

feat: add new APIs: add_policies_ex() and add_named_policies_ex()

---

casbin/async_management_enforcer.py
casbin/management_enforcer.py
casbin/model/policy.py

Continue: https://github.com/casbin/pycasbin/pull/346
fix: fix the bug that get_all_{thing} has wrong result in RBAC with domains model. Previously, #346 has fixed the get_all_named_{thing} function but it did not fix get_all_{thing} function and those functions in async pycasbin.

feat: fix bug that get_all_subjects() and similar APIs get wrong result
